Features/payment
code-in-design/pass-frontend pull request #102
Opened 2023-10-12 06:26 UTC by stnqls

# 배경설명
membership 결제 API연동하기

# 작업내역

bootpay requestPayment호출 후, 성공하면 백엔드로 post
환경설정 > 멤버십 설정 - 결제 내역 작업중

# 레퍼런스

# 주의사항 
1. **PR의 단위는 최대한 작게** 유지해주세요. (300~400라인, File Change 10개 이하 권장)
2. 리뷰어가 빠르게 리뷰할 수 있도록 **배경설명**을 상세하게해주세요 (링크, 스크린샷, 영상등을 포함하면 더 좋습니다.)
3. 특별히 **리뷰가 필요한 코드라인에 코멘트**를 남겨주세요
4. 작업이 완료되기 전 미리 PR을 올려놓고 작업시 발생한 이슈를 해당 PR에 쌓아놨다가 작업이 완료되면 리뷰어에게 리뷰를 요청하셔도 됩니다.

2023-10-12 09:25 UTC, stnqls commented on src/constants/changeScoreTicket.ts
> +export const CHANGESCORETICKET = {
이름 언더바

2023-10-12 09:25 UTC, stnqls commented on src/features/settings/apis/paymentsApi.ts
> +    postPayments: builder.mutation({
실패했을때 alert알려주기

2023-10-12 09:25 UTC, stnqls commented on src/features/settings/components/PaymentTable.tsx
> +          return <PaymentTableItem date={item.date} membership={item.membership} info={item.info} method={item.method} amount={item.amount} status={item.status} />;
key 추가

2023-10-12 09:25 UTC, stnqls commented on src/features/settings/components/PaymentTable.tsx
>  const PaymentTable = (props: Props) => {
paymenthistoryTable

2023-10-12 09:25 UTC, stnqls commented on src/features/settings/containers/MembershipSettingContainer.tsx
> +      orderId: uniqueId(userMe?.id), // 주문ID (매 주문마다 달라야함), 주문자ID + uuid로 orderId 구성
user.id가 uuid앞에 있는지 없는지 확인하기

2023-10-13 03:00 UTC, simsimjae requested changes

2023-10-13 03:00 UTC, simsimjae commented on src/features/settings/containers/MembershipSettingContainer.tsx
> +      orderId: uuidv4(), // 주문ID (매 주문마다 달라야함), 주문자ID + uuid로 orderId 구성
주석 변경

2023-10-13 03:02 UTC, simsimjae approved these changes

2023-10-13 03:04 UTC, merged