Features/university
code-in-design/pass-frontend pull request #21
Opened 2023-06-30 07:27 UTC by stnqls

# 배경설명
대학찾기 - /university api연동위해 model 정의하기

# 작업내역
대학,학과,실기,지역으로 구분해서 model정의하기

# 레퍼런스

# 주의사항 
1. **PR의 단위는 최대한 작게** 유지해주세요. (300~400라인, File Change 10개 이하 권장)
2. 리뷰어가 빠르게 리뷰할 수 있도록 **배경설명**을 상세하게해주세요 (링크, 스크린샷, 영상등을 포함하면 더 좋습니다.)
3. 특별히 **리뷰가 필요한 코드라인에 코멘트**를 남겨주세요
4. 작업이 완료되기 전 미리 PR을 올려놓고 작업시 발생한 이슈를 해당 PR에 쌓아놨다가 작업이 완료되면 리뷰어에게 리뷰를 요청하셔도 됩니다.

2023-06-30 07:34 UTC, simsimjae requested changes

2023-06-30 07:34 UTC, simsimjae commented on src/features/universities/apis/universityApi.ts
> +        return `/?page=${1}&limit=${20}&range=${10}`;
이 부분은 임시로 처리하신건가요? 숫자들이 하드코딩되어있어서요

2023-06-30 07:34 UTC, simsimjae commented on src/features/universities/apis/universityApi.ts
> +          const universityData = data.result.map((item: any) => universityModel.setModelFromData(item));
data.result가 undefined일 수 있으니 그 부분도 ? 옵셔널체이닝으로 처리하는게 좋을것같습니다.

2023-06-30 07:34 UTC, simsimjae commented on src/features/universities/components/FindUniversity/table/UniversityTable.tsx
> +  console.log(props.data);
삭제

2023-06-30 07:34 UTC, simsimjae commented on src/models/UniversitiesModel.ts
> +  setModelFromData = data => {
이건 객체를 리턴해서 사용하는게 아니고 this.id = data.id와 같은 형식으로 클래스 내부 멤버변수에 값을 할당하고 this를 리턴하게 해주세요

2023-06-30 07:34 UTC, simsimjae commented on src/models/RegionModel.ts
> +  seoul?: string; //서울
지역모델이 이런식으로 정의된게 맞나요? seoul에 대한 key에대해서 string으로 어떤 값이 들어오나요?

region?: "서울" | "경기" .... 이런식으로 각 지역이 value로 쓰이고 key에 해당하는게 따로 있을것같아요

2023-06-30 07:35 UTC, simsimjae requested changes

2023-06-30 07:35 UTC, simsimjae commented on src/models/PracticalApplyModel.ts
> +  달리기10m?: string;
실기종목도 모델로 정의할떄는

id, type 이렇게 두가지만 있으면 되지 않을까 싶은데 이렇게 일일이 정의를 해야하는건가요? 백엔드에서 어떻게 내려오나요?

2023-07-03 04:41 UTC, stnqls commented on src/features/universities/apis/universityApi.ts
> +        return `/?page=${1}&limit=${20}&range=${10}`;
네 infinityscroll구현해야해서 하드코딩으로 해뒀습니다.

2023-07-03 06:13 UTC, simsimjae requested changes

2023-07-03 06:13 UTC, simsimjae commented on src/models/KoreanSubjectModel.ts
> +  koreanRequiredType?: string; //국어 필수반영 : 필수반영, 선택반영, 미반영
아~ 이렇게 정의하라는게 아니었고 SubjectModel하나만 정의하고 타입으로 수능,국어,등등을 구분하게 해주실래요

2023-07-03 06:13 UTC, simsimjae commented on src/models/KoreanSubjectModel.ts
> +  koreanRequiredType?: string; //국어 필수반영 : 필수반영, 선택반영, 미반영
https://chat.openai.com/share/649753dd-dc9f-40c0-86f4-a84a06f163ad

이 내용 참고해서 수정해주시고 이번주 발표주제로 잡아서 발표도 같이 부탁드릴게요

2023-07-03 06:13 UTC, simsimjae commented on src/models/PracticalApplyModel.ts
> +type practicalType = '제자리멀리뛰기' | '서전트' | '좌전굴';
https://chat.openai.com/share/8f5078e7-8152-4890-804e-6bbb58715338

타입정의는 파스칼케이스로 하는걸로 하시죠

2023-07-03 06:13 UTC, simsimjae commented on src/models/PracticalApplyModel.ts
> +type practicalType = '제자리멀리뛰기' | '서전트' | '좌전굴';
3개 타입말고 더 많은 타입이 있어야할것같은데 3개만 두신 이유가 있나요

2023-07-03 06:13 UTC, simsimjae commented on src/models/PracticalApplyModel.ts
> +  }
클래스의 멤버함수로 set을 썼다는건 멤버 변수에 인자로 받은 값을 설정하겠다는 뜻인데

이 함수는 지금 받은걸 그대로 리턴만 하고 있습니다.

this.type = types;와 같이 할당을 하거나
의도에 맞게 함수 이름을 변경해주세요

2023-07-03 06:13 UTC, simsimjae commented on src/models/RegionModel.ts
> -  name?: string;
여기는 왜 지우기만 하고 변경이 안되었나요?

2023-07-03 06:13 UTC, simsimjae commented on src/models/UniversityDepartmentsModel.ts
> +  practicalApplyType?: string[];
주석 달아주세요

2023-07-03 06:13 UTC, simsimjae commented on src/models/UniversityDepartmentsModel.ts
> +  subject?: any;
주석달아주시고 이건 뭔가요? any타입이네요

2023-07-03 08:59 UTC, merged