Features/query string
code-in-design/pass-frontend pull request #29
Opened 2023-07-06 08:33 UTC by stnqls

# 배경설명
대학찾기 필터 쿼리스트링

# 작업내역
1. 카테고리 선택후 필터열었을때 첫번째 값 선택되어있는 문제 해결하기
2. 필터 쿼리스트링 수정하기

# 레퍼런스

# 주의사항 
1. **PR의 단위는 최대한 작게** 유지해주세요. (300~400라인, File Change 10개 이하 권장)
3. 리뷰어가 빠르게 리뷰할 수 있도록 **배경설명**을 상세하게해주세요 (링크, 스크린샷, 영상등을 포함하면 더 좋습니다.)
4. 특별히 **리뷰가 필요한 코드라인에 코멘트**를 남겨주세요
5. 작업이 완료되기 전 미리 PR을 올려놓고 작업시 발생한 이슈를 해당 PR에 쌓아놨다가 작업이 완료되면 리뷰어에게 리뷰를 요청하셔도 됩니다.

2023-07-07 07:24 UTC, simsimjae requested changes

2023-07-07 07:24 UTC, simsimjae commented on src/features/universities/components/FindUniversity/UniversityCategoryList.tsx
> +        const filterApply = remove(keys(query), removeItem => removeItem !== 'searchUniversity');
동사 -> 명사로 네이밍 수정

2023-07-07 07:24 UTC, simsimjae commented on src/features/universities/components/FindUniversity/UniversityCategoryList.tsx
> +        const filterApply = remove(keys(query), removeItem => removeItem !== 'searchUniversity');
searchUniversity는 뭔가요?

2023-07-07 07:24 UTC, simsimjae commented on src/features/universities/components/FindUniversity/UniversityCategoryList.tsx
> +  searchUniversity: any;
주석달아주시고 searchUniversity 이게 뭔지 모르겠네요

2023-07-07 07:24 UTC, simsimjae commented on src/features/universities/components/FindUniversity/UniversitySearch.tsx
> +  onInputChange: (e) => void;
e에 타입달아주면 더 좋을듯해요

2023-07-07 07:24 UTC, simsimjae commented on src/features/universities/containers/UniversityCategoryContainer.tsx
> +    if (title === '인기계열') setQuery({ department: [text!], searchUniversity: query.searchUniversity }, 'replace');
여기 코드를 읽고나서야 searchUniversity가 뭔지 유추할 수 있게 되었는데요

searchUniversity -> 동사여서 일단 명사로 수정이 필요하고

대학이름으로 필터링하는걸 의미하는것같은데 그럼 searchUniversity  이런 네이밍보다는 universityName이라고 네이밍 하는게 더 좋지 않을까요?universityName=서울대

2023-07-07 07:29 UTC, stnqls commented on src/features/universities/containers/UniversityCategoryContainer.tsx
> +    if (title === '인기계열') setQuery({ department: [text!], searchUniversity: query.searchUniversity }, 'replace');
디스크립션 보면 대학명 학과명 기준으로 검색이 가능하다고 나와있어서 검색 search를 넣은거긴한데, universityName으로 할까요?

2023-07-07 07:30 UTC, simsimjae commented on src/features/universities/containers/UniversityCategoryContainer.tsx
> +    if (title === '인기계열') setQuery({ department: [text!], searchUniversity: query.searchUniversity }, 'replace');
![image](https://github.com/code-in-design/pass-frontend/assets/29771088/9ee07b73-b526-4fe4-804d-0ce9f64a640c)

2023-07-10 01:47 UTC, simsimjae approved these changes

2023-07-10 01:47 UTC, simsimjae commented on src/features/universities/components/FindUniversity/UniversityCategoryList.tsx
> +        if (filterApplyList.length >= 2) isSelected = false;
주석 추가

2023-07-10 01:49 UTC, merged