Fix/admin page navbar
code-in-design/pass-frontend pull request #37
Opened 2023-07-11 06:45 UTC by dihoon

# 배경설명
관리자 페이지에서 네비게이션 바 메뉴에 하위 메뉴가 있다.
기존 메뉴에서 하위 메뉴가 있는 경우 클릭 시 하위 메뉴가 보이도록 해야한다.

# 작업내역
Navbar 수정
NavbarItem 수정
서브메뉴 추가

# 레퍼런스

# 주의사항 
1. **PR의 단위는 최대한 작게** 유지해주세요. (300~400라인, File Change 10개 이하 권장)
2. 리뷰어가 빠르게 리뷰할 수 있도록 **배경설명**을 상세하게해주세요 (링크, 스크린샷, 영상등을 포함하면 더 좋습니다.)
3. 특별히 **리뷰가 필요한 코드라인에 코멘트**를 남겨주세요
4. 작업이 완료되기 전 미리 PR을 올려놓고 작업시 발생한 이슈를 해당 PR에 쌓아놨다가 작업이 완료되면 리뷰어에게 리뷰를 요청하셔도 됩니다.

2023-07-11 07:03 UTC, simsimjae requested changes

2023-07-11 07:03 UTC, simsimjae commented on src/components/Navbar/index.tsx
> +  menuList: { icon: ReactNode; title: string; route: string; subMenu?: SubMenu[] }[];
복수인경우 끝에 s를 붙여주세요

2023-07-11 07:03 UTC, simsimjae commented on src/components/Navbar/index.tsx
> +    if (startsWith(currentPath, route)) return true;
윗라인이랑 순서를 바꾸는게 좋아보입니다

2023-07-11 07:03 UTC, simsimjae commented on src/components/Navbar/index.tsx
> +    if (startsWith(currentPath, route)) return true;
if문으로만 코드를 작성하면 더 좋을것같습니다.
http://redutan.github.io/2016/04/01/good-if

2023-07-11 07:57 UTC, simsimjae requested changes

2023-07-11 07:57 UTC, simsimjae commented on src/components/Navbar/index.tsx
> +    if (parentPath !== '' && startsWith(currentPath, parentPath)) return true;
이 부분 코드만 보면 어떤 조건인지 잘 모르겠어요 주석을 추가하든 코드 네이밍을 변수로 한번더 하든 해야할것같아요

2023-07-11 08:25 UTC, dihoon commented on src/components/Navbar/index.tsx
>    const isPathActive = (currentPath, route) => {
메뉴에 설정된 라우트 경로를 의미합니다.

2023-07-11 09:27 UTC, simsimjae commented
s

2023-07-11 09:50 UTC, simsimjae commented
새로운댓글

2023-07-12 00:23 UTC, simsimjae commented
ㄴㅇㄹ

2023-07-12 00:24 UTC, merged