Feature/score sheet
code-in-design/pass-frontend pull request #41
Opened 2023-07-13 00:32 UTC by dihoon

# 배경설명
어드민 페이지 수능 분석

# 작업내역
수능 점수표 페이지 작업

# 레퍼런스

# 주의사항 
1. **PR의 단위는 최대한 작게** 유지해주세요. (300~400라인, File Change 10개 이하 권장)
2. 리뷰어가 빠르게 리뷰할 수 있도록 **배경설명**을 상세하게해주세요 (링크, 스크린샷, 영상등을 포함하면 더 좋습니다.)
3. 특별히 **리뷰가 필요한 코드라인에 코멘트**를 남겨주세요
4. 작업이 완료되기 전 미리 PR을 올려놓고 작업시 발생한 이슈를 해당 PR에 쌓아놨다가 작업이 완료되면 리뷰어에게 리뷰를 요청하셔도 됩니다.

2023-07-13 01:01 UTC, simsimjae requested changes

2023-07-13 01:01 UTC, simsimjae commented on src/features/admin/adminScoreSheet/containers/VersionDropDownContainer.tsx
> +const VersionDropDownContainer = () => {
VersionDropDownContainer 제거하거나 훅으로 분리하거나

2023-07-13 09:33 UTC, simsimjae requested changes

2023-07-13 09:33 UTC, simsimjae commented on src/features/admin/adminScoreSheet/components/UploadErrorMessage.tsx
> +const UploadErrorMessage = ({ isHidden }) => {
네이밍 변경 및 props 추가

2023-07-13 09:33 UTC, simsimjae commented on src/features/admin/adminScoreSheet/components/VersionToApplyTestScoreSheet.tsx
> +import { Checkbox } from '@chakra-ui/react';
마찬가지로 공통화

2023-07-13 09:33 UTC, simsimjae commented on src/features/admin/adminScoreSheet/components/VersionToApplyTestScoreSheet.tsx
> +      </Checkbox>
공통화 하고 register로 동작하게끔 수정

2023-07-13 09:33 UTC, simsimjae commented on src/features/admin/adminScoreSheet/containers/ScoreSheetContainer.tsx
> +  const methods = useForm();
defaultValues 넣기

2023-07-13 09:33 UTC, simsimjae commented on src/features/admin/adminScoreSheet/containers/ScoreSheetContainer.tsx
> +        <RadioButtonGroup grade={grade} />
위치 변경 및 전반적인 리팩토링

2023-07-13 09:33 UTC, simsimjae commented on src/features/admin/adminScoreSheet/containers/ScoreSheetContainer.tsx
> +          <CsvUploader file={file} />
file 안받게 수젇ㅇ

2023-07-13 09:33 UTC, simsimjae commented on src/features/admin/adminScoreSheet/containers/VersionToApplyTestScoreSheetContainer.tsx
> +  register('isApplyPreviousVersion');
defaultValues 변경

2023-07-13 09:33 UTC, simsimjae commented on src/theme/components/checkbox.ts
> +  }),
체크박스 컴포넌트만들고 프로젝트 내의 다른 체크박스 전부 만든걸로 교체하기

2023-07-14 02:46 UTC, simsimjae requested changes
앞으로는 PR또는 리뷰반영시 한번 체크하고 리뷰요청해주세요~ 콘솔같은것도 제거가 안되어있고 제가 리뷰했던것들이 가끔 누락되어서 한번 체크하고 요청해주세요~

2023-07-14 02:46 UTC, simsimjae commented on src/components/Layout/AdminLayout.tsx
> +            ],
이거 한줄로 떨어지게 가능한가요? subMenus뒤에있는 콤마 제거하고 저장하면 될수도있어요 시도해봐주시고 안되면 그냥 이대로 가시죠

2023-07-14 02:46 UTC, simsimjae commented on src/constants/path.ts
> +  SCORETABLE_UPLOAD: '/testAnalysis/scoreTableUpload', // 수능 분석 > 수능 점수표
SCORETABLE이 아니라 SCORE_TABLE로 하는게 더 보기 좋을것같아요

수능점수표란, 공식 성적표가 발부되기 전 가채점기간에 유저가 모의고사점수나 수능성적을 입력했을때 패스 내부 데이터로 예상 수능점수를 예측하는 표입니다. 현재 타이틀 이름은 수능점수표로 되어있는데 사실상 수능예상점수표라고 표현하는것이 더 좋을것같습니다. TEST_SCORE_PREVIEW_TABLE_UPLOAD 로 하면 이해가 더 쉬울것같아요

2023-07-14 02:46 UTC, simsimjae commented on src/features/admin/adminScoreTableUpload/components/CsvUploader.tsx
> +  console.log('isUpload', isUploaded);
콘솔 잘 제거하고 올려주세요

2023-07-14 02:46 UTC, simsimjae commented on src/features/admin/adminScoreTableUpload/components/CsvUploader.tsx
> +            <FileUploadInput type="file" {...register('uploadFile')} />
이거 props로 name받아서 등록해야한다고 리뷰했던것같은데 또 하드코딩 되어있네요~

2023-07-14 02:46 UTC, simsimjae commented on src/features/admin/adminScoreTableUpload/components/CsvUploader.tsx
> +      <ErrorMessageWrapper>{formState.errors?.upload?.message && <UploadErrorMessage message={formState.errors.upload?.message as string} />}</ErrorMessageWrapper>
에러메세지도 props로 받아서 넣어야 유연하지 않을까요

2023-07-14 02:46 UTC, simsimjae commented on src/features/admin/adminScoreTableUpload/components/RadionButtonGroup.tsx
> +  const grade = getValues('grade');
여기도 name으로 받게끔 처리가 안되어있어요~

2023-07-14 02:46 UTC, simsimjae commented on src/features/admin/adminScoreTableUpload/components/RadionButtonGroup.tsx
> +            <HiddenRadioInput id={`grade ${index}`} value={option} type="radio" {...register('grade', { required: '학년을 선택하세요' })} />
저번부터 리뷰한게 조금씩 누락생기는게 생기는 것 같아요
제가 리뷰한거 누락되지 않게 신경 잘 써주세요

2023-07-14 02:46 UTC, simsimjae commented on src/features/admin/adminScoreTableUpload/components/VersionToApplyTestScoreSheet.tsx
> +      <Checkbox size="blueCheckBox" {...register('isApplyPreviousVersion')}>
이런거 props로 네임 넣어서 받을수있게해주세요

2023-07-14 02:46 UTC, simsimjae commented on src/features/admin/adminScoreTableUpload/containers/ScoreTableUploadContainer.tsx
> +    } else {
바로 위에서 리턴을 해주고 있어서 else문은 없어도 됩니다.

2023-07-14 02:46 UTC, simsimjae commented on src/features/admin/adminScoreTableUpload/containers/ScoreTableUploadContainer.tsx
> +    if (isEmpty(data.uploadFile) && !data.versionToApply && !data.TobeAppliedVersionId) {
이 문장은 맨위로가게 해주세요

2023-07-14 02:46 UTC, simsimjae commented on src/features/admin/adminScoreTableUpload/containers/ScoreTableUploadContainer.tsx
> +      alert('점수표를 적용할 파일을 업로드하거나 선택해주세요');
선택해주세요에 주어가 빠졌어요

2023-07-14 02:46 UTC, simsimjae commented on src/features/admin/adminScoreTableUpload/containers/ScoreTableUploadContainer.tsx
> +      alert('점수표를 적용할 파일을 업로드하거나 선택해주세요');
데이터 동일 버튼을 선택해주세요 가 맞지 않을까요

2023-07-14 02:46 UTC, simsimjae commented on src/features/admin/adminScoreTableUpload/containers/ScoreTableUploadContainer.tsx
> +      alert('점수표를 적용할 파일을 업로드하거나 선택해주세요');
"점수표를 적용할 파일" -> 문장이 어색합니다. -> 예상점수표 파일을 업로드하거나 데이터동일을 체크해주세요 이렇게 표현해야하지않을까요

2023-07-14 02:46 UTC, simsimjae commented on src/features/admin/adminScoreTableUpload/containers/ScoreTableUploadContainer.tsx
> +    clearErrors('upload');
근데 지금 고3이상, 고2, 고1 각각 라디오버튼을 눌렀을때 같은 버전에서 총3개의 파일이 업로드 될 수 있을것같은데 그거 처리되어있는건가요?

2023-07-14 02:46 UTC, simsimjae commented on src/features/admin/adminScoreTableUpload/containers/ScoreTableUploadContainer.tsx
> +            <Button isDisabled={!isUploaded} onClick={() => onReset()} flex={1} height="56px" padding="16px 10px" backgroundColor={theme.colors.gray1} borderRadius="16px">
이런건 그냥 onClick={onReset} 해도됩니다.

2023-07-14 06:49 UTC, dihoon commented on src/features/admin/adminScoreTableUpload/containers/ScoreTableUploadContainer.tsx
> +    clearErrors('upload');
아직 처리 안했는데 api 나오면 하는 건 어떨까요?

2023-07-14 07:12 UTC, simsimjae commented on src/features/admin/adminScoreTableUpload/containers/ScoreTableUploadContainer.tsx
> +    clearErrors('upload');
네 API 나오고 처리해주세요

2023-07-14 08:30 UTC, simsimjae requested changes

2023-07-14 09:09 UTC, simsimjae approved these changes

2023-07-14 09:09 UTC, merged