Features/mobile sign
code-in-design/pass-frontend pull request #56
Opened 2023-07-20 06:54 UTC by stnqls

# 배경설명
로그인 화면 모바일작업

# 작업내역
1. 로그인 모바일
2. 회원가입완료 alert추가
3. university infinity scroll 사용 안함

# 레퍼런스

# 주의사항 
1. **PR의 단위는 최대한 작게** 유지해주세요. (300~400라인, File Change 10개 이하 권장)
4. 리뷰어가 빠르게 리뷰할 수 있도록 **배경설명**을 상세하게해주세요 (링크, 스크린샷, 영상등을 포함하면 더 좋습니다.)
5. 특별히 **리뷰가 필요한 코드라인에 코멘트**를 남겨주세요
6. 작업이 완료되기 전 미리 PR을 올려놓고 작업시 발생한 이슈를 해당 PR에 쌓아놨다가 작업이 완료되면 리뷰어에게 리뷰를 요청하셔도 됩니다.

2023-07-21 00:45 UTC, simsimjae requested changes

2023-07-21 00:45 UTC, simsimjae commented on src/context/BreakPointContext.tsx
> +};
use breakpoint 추가

2023-07-21 00:45 UTC, simsimjae commented on src/context/BreakPointContext.tsx
> +  return isPc;
isPc, isMobile

2023-07-21 00:45 UTC, simsimjae commented on src/features/auth/components/SignUp/SignUp3.tsx
> +          {isPc ? (
isPc &&

!isPc &&

2023-07-21 05:01 UTC, stnqls commented on src/context/BreakPointContext.tsx
> +  const handleResize = () => {
window의 width사이즈가 변경될때마다 이 함수는 계속 실행되는데, 이 함수가 계속 실행되지 않도록 search에 사용 했던 것 처럼 debounce를 사용하는건가요?

2023-07-24 05:14 UTC, simsimjae requested changes

2023-07-24 05:14 UTC, simsimjae commented on src/models/PracticalApplyGroupModel.ts
> +    }
이게 아니고 
멤버변수로 PracticalModel의 배열을 들고있어야해요

2023-07-24 05:51 UTC, simsimjae requested changes

2023-07-24 05:51 UTC, simsimjae commented on src/models/PracticalApplyGroupModel.ts
> +  groupList?: PracticalApplyModel[];
이거는 그룹리스트를 들고있는게 아니라 실기리스트를 들고있는거니까 이름이 잘못되었네요

2023-07-24 05:51 UTC, simsimjae commented on src/models/PracticalApplyGroupModel.ts
> +      return [PracticalApplyModel.fromApiResponse('제자리 멀리뛰기'), PracticalApplyModel.fromApiResponse('서전트점프')];
인자로 string을 받으면 안되고 api응답 데이터를 받아야해요

2023-07-24 05:51 UTC, simsimjae commented on src/models/PracticalApplyGroupModel.ts
> +  static setPracticalApplyGroup(type: PracticalGroupType) {
set함수는 static이면 안됩니다~ 객체지향 강의 한번 쭉 듣고나서 작업하는게 좋을것같아요

2023-07-24 05:51 UTC, simsimjae commented on src/models/PracticalApplyGroupModel.ts
> +  static setPracticalApplyGroup(type: PracticalGroupType) {
우선 방금 구매한 강의 필요한것만 스킵해가면서 쭉 들어보시겠어요

2023-07-24 08:14 UTC, merged