Features/pass analysis table
code-in-design/pass-frontend pull request #9
Opened 2023-06-20 01:48 UTC by stnqls

# 배경설명
합격분석페이지 지원가능분석 테이블 퍼블리싱하기

# 작업내역
지원가능분석 테이블
합격 분석 열람권이 없을 경우화면 퍼블리싱
대학교 업데이트중일경우 화면 퍼블리싱

# 레퍼런스

# 주의사항 
1. **PR의 단위는 최대한 작게** 유지해주세요. (300~400라인, File Change 10개 이하 권장)
2. 리뷰어가 빠르게 리뷰할 수 있도록 **배경설명**을 상세하게해주세요 (링크, 스크린샷, 영상등을 포함하면 더 좋습니다.)
3. 특별히 **리뷰가 필요한 코드라인에 코멘트**를 남겨주세요
4. 작업이 완료되기 전 미리 PR을 올려놓고 작업시 발생한 이슈를 해당 PR에 쌓아놨다가 작업이 완료되면 리뷰어에게 리뷰를 요청하셔도 됩니다.

2023-06-20 02:27 UTC, simsimjae requested changes

2023-06-20 02:27 UTC, simsimjae commented on src/features/passAnalysis/components/NoMembership.tsx
> +          남아있는 합격 분석 열람권 개수 <span>1개</span>
여기 숫자는 Props로 받아서 내려줄것으로 예상되기때문에 props로 받아서 넘기고 deafultProps로 1을 넣도록 수정해주세요~!

2023-06-20 02:27 UTC, simsimjae commented on src/features/passAnalysis/components/PassAnalysisUniversityLists.tsx
네이밍 좋네요 이름만보고 어디를 의미하는건지 바로 알아들었습니다.

2023-06-20 02:27 UTC, simsimjae commented on src/features/passAnalysis/components/UpdateAnalysis.tsx
> +const UpdateAnalysis = () => {
컴포넌트이름이 동사로 지어졌네요 명사로 변경해주세요

2023-06-20 02:27 UTC, simsimjae commented on src/features/passAnalysis/components/UpdateAnalysis.tsx
> +          2024년 01월 06일 00시
props로 받아서 넣어주세요

2023-06-20 02:27 UTC, simsimjae commented on src/pages/passAnalysis/index.tsx
>                  <NoAnalysisUniversity />
NoAnalysis -> 분석이 없다(X)
서비스하지 않는을 영어로 표현해서 다시 네이밍 해주세요!

2023-06-20 02:27 UTC, simsimjae commented on src/pages/passAnalysis/index.tsx
> +                {/* 업데이트예정일 경우 */}
어떤게 업데이트예정인지 좀 더 구체적이면 좋을것같아요

2023-06-20 02:45 UTC, simsimjae requested changes

2023-06-20 02:45 UTC, simsimjae commented on src/features/passAnalysis/components/PassAnalysisUniversityLists.tsx
> +const SupportabilityRenderer = props => {
CollegeApplicationPossibility

2023-06-20 02:45 UTC, simsimjae commented on src/features/passAnalysis/components/PassAnalysisUniversityLists.tsx
> +const SupportabilityRenderer = props => {
src/components -> Tag -> 좀 더 유연하게 컴포넌트를 만들었으나 일일이 넣어줘야해서 약간 불편함

src/components -> ApplicationPossibilityTag -> 프로젝트에 종속적이되, 좀 더 편리하게 사용 가능함.

2023-06-20 02:45 UTC, simsimjae commented on src/features/passAnalysis/components/PassAnalysisUniversityLists.tsx
> +    if (gridApi) {
주석달기

2023-06-20 02:45 UTC, simsimjae commented on src/features/passAnalysis/components/PassAnalysisUniversityLists.tsx
> +        width: '100%',
styled-components로 수정

2023-06-20 07:55 UTC, stnqls commented on src/features/passAnalysis/container/PracticalChangeScoreContainer.tsx
> +
학교마다 실기 종목이랑 개수가 다르니까 저 practicalChangeScoreForm을 반복되게 하고싶은데 어떻게 해야할지 모르겠어요

2023-06-23 04:24 UTC, simsimjae requested changes

2023-06-23 04:24 UTC, simsimjae commented on src/components/Modal/MembershipModal/MembershipModal.tsx
> +          <MembershipPriceCard key={index} name={item.name} price={item.price} text={item.text} button={item.button} descriptions={item.descriptions} img={item.img} colorText={item.colorText} />
qwegwqeg

2023-06-28 04:03 UTC, merged